### ISSUE TITLE
调整外观后访问首页提示 500 Database Query Error

### ISSUE THREAD

**Issue by HuanCheng65** [liaocp666/Jasmine#51]
Typecho 版本 1.2.1，数据库使用 postgresql
直接启用主题时可以正常访问，在后台修改ICP备案号之后再访问就无法访问
报错：
```
[Wed Mar 20 11:23:09.251608 2024] [php:error] [pid 40] [client 172.18.0.1:55542] PHP Fatal error:  Uncaught Typecho\\Db\\Adapter\\SQLException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: ""\nLINE 1: ...ips."mid"  WHERE  (typecho_relationships."mid" <> '' ) AND (...\n                                                             ^ in /app/var/Typecho/Db/Adapter/Pdo.php:111\nStack trace:\n#0 /app/var/Typecho/Db/Adapter/Pdo/Pgsql.php(54): Typecho\\Db\\Adapter\\Pdo->query('SELECT DISTINCT...', Object(PDO), 1, 'SELECT', 'typecho_content...')\n#1 /app/var/Typecho/Db.php(391): Typecho\\Db\\Adapter\\Pdo\\Pgsql->query('SELECT DISTINCT...', Object(PDO), 1, 'SELECT', 'typecho_content...')\n#2 /app/var/Typecho/Db.php(424): Typecho\\Db->query(Object(Typecho\\Db\\Query))\n#3 /app/usr/themes/jasmine/core/post.php(32): Typecho\\Db->fetchAll(Object(Typecho\\Db\\Query), Array)\n#4 /app/usr/themes/jasmine/component/sidebar.php(35): getHotPosts()\n#5 /app/var/Widget/Archive.php(1336): require('/app/usr/themes...')\n#6 /app/usr/themes/jasmine/404.php(28): Widget\\Archive->need('component/sideb...')\n#7 /app/var/Widget/Archive.php(1418): require_once('/app/usr/themes...')\n#8 /app/var/Widget/ExceptionHandle.php(25): Widget\\Archive->render()\n#9 /app/var/Typecho/Widget.php(155): Widget\\ExceptionHandle->execute()\n#10 /app/var/Typecho/Widget.php(187): Typecho\\Widget::widget('Widget\\\\Exceptio...', NULL, NULL, true)\n#11 /app/var/Widget/Init.php(47): Typecho\\Widget::alloc()\n#12 [internal function]: Widget\\Init->Widget\\{closure}(Object(Typecho\\Router\\Exception))\n#13 {main}\n  thrown in /app/var/Typecho/Db/Adapter/Pdo.php on line 111
```

**Comment by liaocp666** [comment]
3.0.0 版本修复
